name: Build

on:
  push:
    branches:
      - '**/*'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: 6.0

      - name: Install asdf
        uses: asdf-vm/actions/setup@v1
        with:
          asdf_branch: v0.10.2

      - name: Install Node.js with asdf
        run: |
          asdf plugin add nodejs
          asdf install nodejs

      - name: Install project dependencies
        run: |
          npm ci

      - name: Run automated tests & generate code coverage report
        run: |
          npm run test

      - name: Format code
        run: |
          npm run format

      - name: Generate apiDoc documentation
        run: |
          npm run apidoc
