name: build

on:
  push:
    branches:
      - '**/*'
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: 7.0

      - name: Install asdf
        uses: asdf-vm/actions/setup@v3
        with:
          asdf_branch: v0.14.1

      - name: Install Node.js with asdf
        run: |
          asdf plugin add nodejs
          asdf install nodejs

      - name: Install project dependencies
        run: |
          npm ci

      - name: Run automated tests & generate code coverage report
        run: |
          npm run test

      - name: Format code
        run: |
          npm run format

      - name: Generate apiDoc documentation
        run: |
          npm run apidoc
