name: build

on:
  push:
    branches:
      - '**/*'
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: 8.0

      - name: Install asdf
        uses: asdf-vm/actions/install@v4
        with:
          asdf_version: v0.18.0

      - name: Install project dependencies
        run: |
          npm ci

      - name: Run automated tests & generate code coverage report
        run: |
          npm run test

      - name: Format code
        run: |
          npm run format

      - name: Ensure there are no uncommitted changes
        run: |
          git status --porcelain
          test -z "$(git status --porcelain)"
